# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Static website
email: mihai@ilincescu.ro
description: > # Static websites are awesome yay!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vidpub.com" # the base hostname & protocol for your site
twitter_username: IlincescuMihai
github_username:  IlincescuMihai
permalink: "/products/:title"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
